export const GET_BANNER_LIST = 'GET_BANNER_LIST';
export const GET_MOVIES_LIST = 'GET_MOVIES_LIST';
export const GET_CINEMA_SYSTEM = 'GET_CINEMA_SYSTEM';
export const GET_CINEMA_BY_CODE = 'GET_CINEMA_BY_CODE';
export const GET_SHOW_SCHEDULE = 'GET_SHOW_SCHEDULE';
export const CHANGE_CODE_CINEMA = 'CHANGE_CODE_CINEMA';
export const SIGN_IN = 'SIGN_IN';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';

